services:
  mysql:
    container_name: 'emailsenderdb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=emailmicroservicedb'
      - 'MYSQL_PASSWORD=Numsey@Password!'
      - 'MYSQL_ROOT_PASSWORD=Numsey@Password!!'
      - 'MYSQL_USER=myuser'
    ports:
      - '3310:3306'
  emailservice:
    container_name: 'emailmicroservice'
    image: 'emailsender:latest'
    ports:
      - '8080:8080'
    restart: unless-stopped
    
  